import { z } from "zod"

export const PostAdminCreateCarModel = z.object({
    name: z.string(),
    title: z.string().optional(),
    intro: z.string().optional(),
    description: z.string().optional(),
    image: z.string().optional(),
    PictureId:z.string().optional(),
    Description:z.string().optional(),
    MetaKeywords:z.string().optional(),
    MetaDescription:z.string().optional(),
    MetaTitle:z.string().optional(),
    Published: z.string().optional(),
    Deleted: z.string().optional(),
    DisplayOrder: z.string().optional(),
    CreatedOnUtc: z.string().optional(),
    UpdatedOnUtc: z.string().optional(),
    ModelBannerId:z.string().optional(),
    ChargingStationDescription:z.string().optional(),
    ChargingCableDescription:z.string().optional(),
    AccessoriesDescription:z.string().optional(),
    ModelBannerDescription:z.string().optional(),
    CableType:z.string().optional(),
    is1F16A:z.string().optional(),
    is1F32A:z.string().optional(),
    is3F16A:z.string().optional(),
    is3F32A:z.string().optional(),
    CablePictureId:z.string().optional(),
    StructuredData:z.string().optional(),
    H1Title:z.string().optional(),
}) as any